# base-app values — Hercules API (Deployment + Service + Ingress).
fullnameOverride: api
project: hercules
env: local

image:
  repository: hashicorp/http-echo # public Docker Hub image
  tag: "0.2.3"
  pullPolicy: IfNotPresent

deployment:
  enabled: true
  containerPort: 8080
  args:
    - "-listen=:8080"
    - "-text=hercules api"

service:
  enabled: true
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: hercules-api.127.0.0.1.nip.io

probes:
  enabled: true
  liveness:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 5
  readiness:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 3
